# Site settings
title:          Verhalen van Jay
description:    "Life of Jay"
baseurl:        ""
url:            "https://chesterhow.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Gaius Bestiae
  url:        
  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:day-:month-:year/:title
paginate:       4

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
